<?php

namespace MailVotech\LeadBundle\Form\Type;

use MailVotech\CategoryBundle\Form\Type\CategoryListType;
use MailVotech\CoreBundle\Form\EventListener\CleanFormSubscriber;
use MailVotech\CoreBundle\Form\EventListener\FormExitSubscriber;
use MailVotech\CoreBundle\Form\Type\FormButtonsType;
use MailVotech\CoreBundle\Form\Type\YesNoButtonGroupType;
use MailVotech\CoreBundle\Form\Validator\Constraints\CircularDependency;
use MailVotech\LeadBundle\Entity\LeadList;
use MailVotech\LeadBundle\Form\DataTransformer\FieldFilterTransformer;
use MailVotech\LeadBundle\Model\ListModel;
use MailVotech\LeadBundle\Provider\TypeOperatorProviderInterface;
use MailVotech\LeadBundle\Segment\RelativeDate;
use MailVotech\LeadBundle\Validator\Constraints\SegmentDate;
use MailVotech\ProjectBundle\Form\Type\ProjectType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @extends AbstractType<LeadList>
 */
final class ListType extends AbstractType
{
    public function __construct(
        private readonly TranslatorInterface $translator,
        private readonly ListModel $listModel,
        private readonly RelativeDate $relativeDate,
        TypeOperatorProviderInterface $typeOperatorProvider,
    ) {
        $typeOperatorProvider->setContext('segment');
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->addEventSubscriber(new CleanFormSubscriber(['description' => 'html', 'name' => 'string', 'publicName' => 'string', 'filter' => 'raw']));
        $builder->addEventSubscriber(new FormExitSubscriber('lead.list', $options));

        $builder->add(
            'name',
            TextType::class,
            [
                'label'      => 'mailvotech.core.name',
                'label_attr' => ['class' => 'control-label'],
                'attr'       => ['class' => 'form-control'],
            ]
        );

        $builder->add(
            'publicName',
            TextType::class,
            [
                'label'      => 'mailvotech.lead.list.form.publicname',
                'label_attr' => ['class' => 'control-label'],
                'attr'       => [
                    'class'       => 'form-control',
                    'tooltip'     => 'mailvotech.lead.list.form.publicname.tooltip',
                    'placeholder' => 'mailvotech.core.autogenerated',
                ],
                'required' => false,
            ]
        );

        $builder->add(
            'alias',
            TextType::class,
            [
                'label'      => 'mailvotech.core.alias',
                'label_attr' => ['class' => 'control-label'],
                'attr'       => [
                    'class'       => 'form-control',
                    'length'      => 25,
                    'tooltip'     => 'mailvotech.lead.list.help.alias',
                    'placeholder' => 'mailvotech.core.autogenerated',
                ],
                'required' => false,
            ]
        );

        $builder->add(
            'description',
            TextareaType::class,
            [
                'label'      => 'mailvotech.core.description',
                'label_attr' => ['class' => 'control-label'],
                'attr'       => ['class' => 'form-control editor'],
                'required'   => false,
            ]
        );

        $builder->add(
            'category',
            CategoryListType::class,
            [
                'bundle' => 'segment',
            ]
        );

        $builder->add(
            'isGlobal',
            YesNoButtonGroupType::class,
            [
                'label'      => 'mailvotech.lead.list.form.isglobal',
                'attr'       => [
                    'tooltip' => 'mailvotech.lead.list.form.isglobal.tooltip',
                ],
                'no_label'   => 'mailvotech.lead.list.form.isglobal.no',
            ]
        );

        $builder->add(
            'isPreferenceCenter',
            YesNoButtonGroupType::class,
            [
                'label'      => 'mailvotech.lead.list.form.isPreferenceCenter',
                'attr'       => [
                    'tooltip' => 'mailvotech.lead.list.form.isPreferenceCenter.tooltip',
                ],
            ]
        );

        $builder->add('projects', ProjectType::class);
        $builder->add('isPublished', YesNoButtonGroupType::class);

        $filterModalTransformer = new FieldFilterTransformer($this->translator, $this->relativeDate, ['object' => 'lead']);
        $builder->add(
            $builder->create(
                'filters',
                CollectionType::class,
                [
                    'entry_type'     => FilterType::class,
                    'error_bubbling' => false,
                    'mapped'         => true,
                    'allow_add'      => true,
                    'allow_delete'   => true,
                    'label'          => false,
                    'constraints'    => [
                        new CircularDependency(message: 'mailvotech.core.segment.circular_dependency_exists'),
                        new SegmentDate(message: 'mailvotech.lead.segment.date_invalid'),
                    ],
                ]
            )->addModelTransformer($filterModalTransformer)
        );

        $builder->add('buttons', FormButtonsType::class);

        if (!empty($options['action'])) {
            $builder->setAction($options['action']);
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(
            [
                'data_class' => LeadList::class,
            ]
        );
    }

    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        $view->vars['fields'] = $this->listModel->getChoiceFields();
    }

    public function getBlockPrefix(): string
    {
        return 'leadlist';
    }
}
