blank_issues_enabled: false
contact_links:
  - name: MailVotech Community Support
    url: https://forum.mailvotech.org/c/support
    about: Please ask and answer support questions here.
  - name: MailVotech Feature Requests
    url: https://forum.mailvotech.org/c/ideas
    about: We use GitHub issues as a bug tracker only. Please go to https://forum.mailvotech.org/c/ideas to find support and discuss features/ideas.
