<?php

declare(strict_types=1);

return [
    'routes' => [
        'main' => [
            'mailvotech_core_ajax' => [
                'path'       => '/ajax',
                'controller' => 'MailVotech\CoreBundle\Controller\AjaxController::delegateAjaxAction',
            ],
            'mailvotech_core_form_action' => [
                'path'       => '/action/{objectAction}/{objectModel}/{objectId}',
                'controller' => 'MailVotech\CoreBundle\Controller\FormController::executeAction',
                'defaults'   => [
                    'objectModel' => '',
                ],
            ],
            'mailvotech_core_file_action' => [
                'path'       => '/file/{objectAction}/{objectId}',
                'controller' => 'MailVotech\CoreBundle\Controller\FileController::executeAction',
            ],
            'mailvotech_themes_index' => [
                'path'       => '/themes',
                'controller' => 'MailVotech\CoreBundle\Controller\ThemeController::indexAction',
            ],
            'mailvotech_themes_action' => [
                'path'       => '/themes/{objectAction}/{objectId}',
                'controller' => 'MailVotech\CoreBundle\Controller\ThemeController::executeAction',
            ],
            'mailvotech_core_keep_alive' => [
                'path'       => '/keep-alive',
                'controller' => 'MailVotech\CoreBundle\Controller\KeepAliveController::keepAliveAction',
            ],
        ],
        'public' => [
            'mailvotech_js' => [
                'path'       => '/mtc.js',
                'controller' => 'MailVotech\CoreBundle\Controller\JsController::indexAction',
            ],
            'mailvotech_essential_js' => [
                'path'       => '/mailvotech-essential.js',
                'controller' => 'MailVotech\CoreBundle\Controller\JsController::essentialAction',
            ],
            'mailvotech_tracking_js' => [
                'path'       => '/mailvotech-tracking.js',
                'controller' => 'MailVotech\CoreBundle\Controller\JsController::trackingAction',
            ],
            'mailvotech_base_index' => [
                'path'       => '/',
                'controller' => 'MailVotech\CoreBundle\Controller\DefaultController::indexAction',
            ],
            'mailvotech_secure_root' => [
                'path'       => '/s',
                'controller' => 'MailVotech\CoreBundle\Controller\DefaultController::redirectSecureRootAction',
            ],
            'mailvotech_secure_root_slash' => [
                'path'       => '/s/',
                'controller' => 'MailVotech\CoreBundle\Controller\DefaultController::redirectSecureRootAction',
            ],
            'mailvotech_remove_trailing_slash' => [
                'path'         => '/{url}',
                'controller'   => 'MailVotech\CoreBundle\Controller\CommonController::removeTrailingSlashAction',
                'method'       => 'GET',
                'requirements' => [
                    'url' => '.*/$',
                ],
            ],
        ],
        'api' => [
            'mailvotech_core_api_file_list' => [
                'path'       => '/files/{dir}',
                'controller' => 'MailVotech\CoreBundle\Controller\Api\FileApiController::listAction',
            ],
            'mailvotech_core_api_file_create' => [
                'path'       => '/files/{dir}/new',
                'controller' => 'MailVotech\CoreBundle\Controller\Api\FileApiController::createAction',
                'method'     => 'POST',
            ],
            'mailvotech_core_api_file_delete' => [
                'path'       => '/files/{dir}/{file}/delete',
                'controller' => 'MailVotech\CoreBundle\Controller\Api\FileApiController::deleteAction',
                'method'     => 'DELETE',
            ],
            'mailvotech_core_api_theme_list' => [
                'path'       => '/themes',
                'controller' => 'MailVotech\CoreBundle\Controller\Api\ThemeApiController::listAction',
            ],
            'mailvotech_core_api_theme_get' => [
                'path'       => '/themes/{theme}',
                'controller' => 'MailVotech\CoreBundle\Controller\Api\ThemeApiController::getAction',
            ],
            'mailvotech_core_api_theme_create' => [
                'path'       => '/themes/new',
                'controller' => 'MailVotech\CoreBundle\Controller\Api\ThemeApiController::newAction',
                'method'     => 'POST',
            ],
            'mailvotech_core_api_theme_delete' => [
                'path'       => '/themes/{theme}/delete',
                'controller' => 'MailVotech\CoreBundle\Controller\Api\ThemeApiController::deleteAction',
                'method'     => 'DELETE',
            ],
            'mailvotech_core_api_stats' => [
                'path'       => '/stats/{table}',
                'controller' => 'MailVotech\CoreBundle\Controller\Api\StatsApiController::listAction',
                'defaults'   => [
                    'table' => '',
                ],
            ],
        ],
    ],
    'menu' => [
        'main' => [
            'mailvotech.core.components' => [
                'id'        => 'mailvotech_components_root',
                'iconClass' => 'ri-archive-2-fill',
                'priority'  => 60,
            ],
            'mailvotech.core.channels' => [
                'id'        => 'mailvotech_channels_root',
                'iconClass' => 'ri-remote-control-fill',
                'priority'  => 40,
            ],
            'mailvotech.contribute.menu.index' => [
                'uri'            => 'https://mau.tc/support',
                'iconClass'      => 'ri-hand-coin-fill',
                'priority'       => 0,
                'linkAttributes' => [
                    'target' => '_blank',
                    'rel'    => 'noopener noreferrer',
                ],
                'checks' => [
                    'parameters' => [
                        'support_mailvotech_enabled' => true,
                    ],
                ],
            ],
        ],
        'admin' => [
            'mailvotech.core.general' => [
                'id'        => 'mailvotech_general_root',
                'priority'  => 15,
            ],
            'mailvotech.theme.menu.index' => [
                'route'     => 'mailvotech_themes_index',
                'iconClass' => 'ri-pantone-line',
                'id'        => 'mailvotech_themes_index',
                'access'    => 'core:themes:view',
                'parent'    => 'mailvotech.core.general',
                'priority'  => 18,
            ],
            'mailvotech.core.integrations' => [
                'id'        => 'mailvotech_integrations_root',
                'priority'  => 15,
            ],
        ],
        'extra' => [
            'priority' => -1000,
            'items'    => [
                'name'     => 'extra',
                'children' => [],
            ],
        ],
        'profile' => [
            'priority' => -1000,
            'items'    => [
                'name'     => 'profile',
                'children' => [],
            ],
        ],
    ],
    'services' => [
        'menus' => [
            'mailvotech.menu.main' => [
                'alias' => 'main',
            ],
            'mailvotech.menu.admin' => [
                'alias'   => 'admin',
                'options' => [
                    'template' => '@MailVotechCore/Menu/admin.html.twig',
                ],
            ],
            'mailvotech.menu.extra' => [
                'alias'   => 'extra',
                'options' => [
                    'template' => '@MailVotechCore/Menu/extra.html.twig',
                ],
            ],
            'mailvotech.menu.profile' => [
                'alias'   => 'profile',
                'options' => [
                    'template' => '@MailVotechCore/Menu/profile_inline.html.twig',
                ],
            ],
        ],
    ],

    'ip_lookup_services' => [
        'extreme-ip' => [
            'display_name' => 'Extreme-IP',
            'class'        => MailVotech\CoreBundle\IpLookup\ExtremeIpLookup::class,
        ],
        'freegeoip' => [
            'display_name' => 'Ipstack.com',
            'class'        => MailVotech\CoreBundle\IpLookup\IpstackLookup::class,
        ],
        'geobytes' => [
            'display_name' => 'Geobytes',
            'class'        => MailVotech\CoreBundle\IpLookup\GeobytesLookup::class,
        ],
        'geoips' => [
            'display_name' => 'GeoIPs',
            'class'        => MailVotech\CoreBundle\IpLookup\GeoipsLookup::class,
        ],
        'ipinfodb' => [
            'display_name' => 'IPInfoDB',
            'class'        => MailVotech\CoreBundle\IpLookup\IpinfodbLookup::class,
        ],
        'maxmind_country' => [
            'display_name' => 'MaxMind - Country Geolocation',
            'class'        => MailVotech\CoreBundle\IpLookup\MaxmindCountryLookup::class,
        ],
        'maxmind_omni' => [
            'display_name' => 'MaxMind - Insights (formerly Omni]',
            'class'        => MailVotech\CoreBundle\IpLookup\MaxmindOmniLookup::class,
        ],
        'maxmind_precision' => [
            'display_name' => 'MaxMind - GeoIP2 Precision',
            'class'        => MailVotech\CoreBundle\IpLookup\MaxmindPrecisionLookup::class,
        ],
        'maxmind_download' => [
            'display_name' => 'MaxMind - GeoLite2 City Download',
            'class'        => MailVotech\CoreBundle\IpLookup\MaxmindDownloadLookup::class,
        ],
        'telize' => [
            'display_name' => 'Telize',
            'class'        => MailVotech\CoreBundle\IpLookup\TelizeLookup::class,
        ],
        'ip2loctionlocal' => [
            'display_name' => 'IP2Location Local Bin File',
            'class'        => MailVotech\CoreBundle\IpLookup\IP2LocationBinLookup::class,
        ],
        'ip2loctionapi' => [
            'display_name' => 'IP2Location Web Service',
            'class'        => MailVotech\CoreBundle\IpLookup\IP2LocationAPILookup::class,
        ],
    ],

    'parameters' => [
        'site_url'                        => '',
        'webroot'                         => '',
        '404_page'                        => '',
        'cache_path'                      => '%kernel.project_dir%/var/cache',
        'log_path'                        => '%kernel.project_dir%/var/logs',
        'max_log_files'                   => 7,
        'log_file_name'                   => 'mailvotech_%kernel.environment%.php',
        'image_path'                      => 'media/images',
        'media_path'                      => 'media',
        'tmp_path'                        => '%kernel.project_dir%/var/tmp',
        'theme'                           => 'blank',
        'theme_import_allowed_extensions' => ['json', 'twig', 'css', 'js', 'htm', 'html', 'txt', 'jpg', 'jpeg', 'png', 'gif'],
        'brand_name'                      => 'Your Brand (configurable)',
        'primary_brand_color'             => '000000',
        'rounded_corners'                 => '0',
        'db_driver'                       => 'pdo_mysql',
        'db_host'                         => '127.0.0.1',
        'db_port'                         => 3306,
        'db_name'                         => '',
        'db_user'                         => '',
        'db_password'                     => '',
        'db_table_prefix'                 => '',
        'db_host_ro'                      => null,
        'locale'                          => 'en_US',
        'secret_key'                      => 'temp',
        'dev_hosts'                       => [],
        'trusted_hosts'                   => [],
        'trusted_proxies'                 => [],
        'validate_remote_domains'         => false, // whether to validate remote domains in remote URLs
        'allowed_remote_domains'          => [],
        'rememberme_key'                  => '%mailvotech.secret_key%',
        'rememberme_lifetime'             => 7_776_000, // 90 days in seconds
        'rememberme_path'                 => '/',
        'rememberme_domain'               => '',
        'default_pagelimit'               => 30,
        'default_timezone'                => 'UTC',
        'date_format_full'                => 'F j, Y g:i a T',
        'date_format_short'               => 'D, M d',
        'date_format_dateonly'            => 'F j, Y',
        'date_format_timeonly'            => 'g:i a',
        'ip_lookup_service'               => 'maxmind_download',
        'ip_lookup_auth'                  => '',
        'ip_lookup_config'                => [],
        'ip_lookup_create_organization'   => false,
        'transifex_api_token'             => '',
        'update_stability'                => 'stable',
        'cookie_path'                     => '/',
        'cookie_domain'                   => '',
        'cookie_secure'                   => true,
        'cookie_httponly'                 => false,
        'do_not_track_ips'                => [],
        'do_not_track_bots'               => [
            'MSNBOT',
            'msnbot-media',
            'bingbot',
            'Googlebot',
            'Google Web Preview',
            'Mediapartners-Google',
            'Baiduspider',
            'Ezooms',
            'YahooSeeker',
            'Slurp',
            'AltaVista',
            'AVSearch',
            'Mercator',
            'Scooter',
            'InfoSeek',
            'Ultraseek',
            'Lycos',
            'Wget',
            'YandexBot',
            'Java/1.4.1_04',
            'SiteBot',
            'Exabot',
            'AhrefsBot',
            'MJ12bot',
            'NetSeer crawler',
            'TurnitinBot',
            'magpie-crawler',
            'Nutch Crawler',
            'CMS Crawler',
            'rogerbot',
            'Domnutch',
            'ssearch_bot',
            'XoviBot',
            'digincore',
            'fr-crawler',
            'SeznamBot',
            'Seznam screenshot-generator',
            'Facebot',
            'facebookexternalhit',
            'SimplePie',
            'Riddler',
            '007ac9 Crawler',
            '360Spider',
            'A6-Indexer',
            'ADmantX',
            'AHC',
            'AISearchBot',
            'APIs-Google',
            'Aboundex',
            'AddThis',
            'Adidxbot',
            'AdsBot-Google',
            'AdsTxtCrawler',
            'AdvBot',
            'Ahrefs',
            'AlphaBot',
            'Amazon CloudFront',
            'AndersPinkBot',
            'Apache-HttpClient',
            'Apercite',
            'AppEngine-Google',
            'Applebot',
            'ArchiveBot',
            'BDCbot',
            'BIGLOTRON',
            'BLEXBot',
            'BLP_bbot',
            'BTWebClient',
            'BUbiNG',
            'Baidu-YunGuanCe',
            'Barkrowler',
            'BehloolBot',
            'BingPreview',
            'BomboraBot',
            'Bot.AraTurka.com',
            'BoxcarBot',
            'BrandVerity',
            'Buck',
            'CC Metadata Scaper',
            'CCBot',
            'CapsuleChecker',
            'Cliqzbot',
            'CloudFlare-AlwaysOnline',
            'Companybook-Crawler',
            'ContextAd Bot',
            'CrunchBot',
            'CrystalSemanticsBot',
            'CyberPatrol',
            'DareBoost',
            'Datafeedwatch',
            'Daum',
            'DeuSu',
            'developers.google.com',
            'Diffbot',
            'Digg Deeper',
            'Digincore bot',
            'Discordbot',
            'Disqus',
            'DnyzBot',
            'Domain Re-Animator Bot',
            'DomainStatsBot',
            'DuckDuckBot',
            'DuckDuckGo-Favicons-Bot',
            'EZID',
            'Embedly',
            'EveryoneSocialBot',
            'ExtLinksBot',
            'FAST Enterprise Crawler',
            'FAST-WebCrawler',
            'Feedfetcher-Google',
            'Feedly',
            'Feedspotbot',
            'FemtosearchBot',
            'Fetch',
            'Fever',
            'Flamingo_SearchEngine',
            'FlipboardProxy',
            'Fyrebot',
            'GarlikCrawler',
            'Genieo',
            'Gigablast',
            'Gigabot',
            'GingerCrawler',
            'Gluten Free Crawler',
            'GnowitNewsbot',
            'Go-http-client',
            'Google-Adwords-Instant',
            'Gowikibot',
            'GrapeshotCrawler',
            'Grobbot',
            'HTTrack',
            'Hatena',
            'IAS crawler',
            'ICC-Crawler',
            'IndeedBot',
            'InterfaxScanBot',
            'IstellaBot',
            'James BOT',
            'Jamie\'s Spider',
            'Jetslide',
            'Jetty',
            'Jugendschutzprogramm-Crawler',
            'K7MLWCBot',
            'Kemvibot',
            'KosmioBot',
            'Landau-Media-Spider',
            'Laserlikebot',
            'Leikibot',
            'Linguee Bot',
            'LinkArchiver',
            'LinkedInBot',
            'LivelapBot',
            'Luminator-robots',
            'Mail.RU_Bot',
            'Mastodon',
            'MauiBot',
            'Mediatoolkitbot',
            'MegaIndex',
            'MeltwaterNews',
            'MetaJobBot',
            'MetaURI',
            'Miniflux',
            'MojeekBot',
            'Moreover',
            'MuckRack',
            'Multiviewbot',
            'NING',
            'NerdByNature.Bot',
            'NetcraftSurveyAgent',
            'Netvibes',
            'Nimbostratus-Bot',
            'Nuzzel',
            'Ocarinabot',
            'OpenHoseBot',
            'OrangeBot',
            'OutclicksBot',
            'PR-CY.RU',
            'PaperLiBot',
            'Pcore-HTTP',
            'PhantomJS',
            'PiplBot',
            'PocketParser',
            'Primalbot',
            'PrivacyAwareBot',
            'Pulsepoint',
            'Python-urllib',
            'Qwantify',
            'RankActiveLinkBot',
            'RetrevoPageAnalyzer',
            'SBL-BOT',
            'SEMrushBot',
            'SEOkicks',
            'SWIMGBot',
            'SafeDNSBot',
            'SafeSearch microdata crawler',
            'ScoutJet',
            'Scrapy',
            'Screaming Frog SEO Spider',
            'SemanticScholarBot',
            'SimpleCrawler',
            'Siteimprove.com',
            'SkypeUriPreview',
            'Slack-ImgProxy',
            'Slackbot',
            'Snacktory',
            'SocialRankIOBot',
            'Sogou',
            'Sonic',
            'StorygizeBot',
            'SurveyBot',
            'Sysomos',
            'TangibleeBot',
            'TelegramBot',
            'Teoma',
            'Thinklab',
            'TinEye',
            'ToutiaoSpider',
            'Traackr.com',
            'Trove',
            'TweetmemeBot',
            'Twitterbot',
            'Twurly',
            'Upflow',
            'UptimeRobot',
            'UsineNouvelleCrawler',
            'Veoozbot',
            'WeSEE:Search',
            'WhatsApp',
            'Xenu Link Sleuth',
            'Y!J',
            'YaK',
            'Yahoo Link Preview',
            'Yeti',
            'YisouSpider',
            'Zabbix',
            'ZoominfoBot',
            'ZumBot',
            'ZuperlistBot',
            '^LCC ',
            'acapbot',
            'acoonbot',
            'adbeat_bot',
            'adscanner',
            'aiHitBot',
            'antibot',
            'arabot',
            'archive.org_bot',
            'axios',
            'backlinkcrawler',
            'betaBot',
            'bibnum.bnf',
            'binlar',
            'bitlybot',
            'blekkobot',
            'blogmuraBot',
            'bnf.fr_bot',
            'bot-pge.chlooe.com',
            'botify',
            'brainobot',
            'buzzbot',
            'cXensebot',
            'careerbot',
            'centurybot9',
            'changedetection',
            'check_http',
            'citeseerxbot',
            'coccoc',
            'collection@infegy.com',
            'content crawler spider',
            'contxbot',
            'convera',
            'crawler4j',
            'curl',
            'datagnionbot',
            'dcrawl',
            'deadlinkchecker',
            'discobot',
            'domaincrawler',
            'dotbot',
            'drupact',
            'ec2linkfinder',
            'edisterbot',
            'electricmonk',
            'elisabot',
            'epicbot',
            'eright',
            'europarchive.org',
            'exabot',
            'ezooms',
            'filterdb.iss.net',
            'findlink',
            'findthatfile',
            'findxbot',
            'fluffy',
            'fuelbot',
            'g00g1e.net',
            'g2reader-bot',
            'gnam gnam spider',
            'google-xrawler',
            'grub.org',
            'gslfbot',
            'heritrix',
            'http_get',
            'httpunit',
            'ia_archiver',
            'ichiro',
            'imrbot',
            'integromedb',
            'intelium_bot',
            'ip-web-crawler.com',
            'ips-agent',
            'iskanie',
            'it2media-domain-crawler',
            'jyxobot',
            'lb-spider',
            'libwww',
            'linkapediabot',
            'linkdex',
            'lipperhey',
            'lssbot',
            'lssrocketcrawler',
            'ltx71',
            'mappydata',
            'memorybot',
            'mindUpBot',
            'mlbot',
            'moatbot',
            'msnbot',
            'msrbot',
            'nerdybot',
            'netEstate NE Crawler',
            'netresearchserver',
            'newsharecounts',
            'newspaper',
            'niki-bot',
            'nutch',
            'okhttp',
            'omgili',
            'openindexspider',
            'page2rss',
            'panscient',
            'phpcrawl',
            'pingdom',
            'pinterest',
            'postrank',
            'proximic',
            'psbot',
            'purebot',
            'python-requests',
            'redditbot',
            'scribdbot',
            'seekbot',
            'semanticbot',
            'sentry',
            'seoscanners',
            'seznambot',
            'sistrix crawler',
            'sitebot',
            'siteexplorer.info',
            'smtbot',
            'spbot',
            'speedy',
            'summify',
            'tagoobot',
            'toplistbot',
            'tracemyfile',
            'trendictionbot',
            'turnitinbot',
            'twengabot',
            'um-LN',
            'urlappendbot',
            'vebidoobot',
            'vkShare',
            'voilabot',
            'wbsearchbot',
            'web-archive-net.com.bot',
            'webcompanycrawler',
            'webmon',
            'wget',
            'wocbot',
            'woobot',
            'woriobot',
            'wotbox',
            'xovibot',
            'yacybot',
            'yandex.com',
            'yanga',
            'yoozBot',
            'zgrab',
        ],
        'do_not_track_internal_ips'           => [],
        'track_private_ip_ranges'             => false,
        'link_shortener_url'                  => null,
        'shortener_email_enable'              => false,
        'shortener_sms_enable'                => true,
        'cached_data_timeout'                 => 10,
        'batch_sleep_time'                    => 1,
        'batch_campaign_sleep_time'           => false,
        'transliterate_page_title'            => false,
        'cors_restrict_domains'               => true,
        'cors_valid_domains'                  => [],
        'headers_sts'                         => false,
        'headers_sts_expire_time'             => 60,
        'headers_sts_subdomains'              => false,
        'headers_sts_preload'                 => false,
        'max_entity_lock_time'                => 0,
        'default_daterange_filter'            => '-1 month',
        'debug'                               => false,
        'anonymize_ip_address_in_background'  => false,
        'rss_notification_url'                => '',
        'motd_url'                            => 'https://mailvotech.github.io/motd/motd.json',
        'motd_cache_path'                     => '%mailvotech.cache_path%/motd.json',
        'motd_cache_ttl'                      => 3600,
        'translations_list_url'               => 'https://language-packs.mailvotech.com/manifest.json',
        'translations_fetch_url'              => 'https://language-packs.mailvotech.com/',
        'stats_update_url'                    => 'https://updates.mailvotech.org/stats/send', // set to empty in config file to disable
        'install_source'                      => 'MailVotech',
        'system_update_url'                   => 'https://api.github.com/repos/mailvotech/mailvotech/releases',
        'editor_fonts'                        => [
            [
                'name' => 'Arial',
                'font' => 'Arial, Helvetica Neue, Helvetica, sans-serif',
            ],
            [
                'name' => 'Bitter',
                'font' => 'Bitter, Georgia, Times, Times New Roman, serif',
                'url'  => 'https://fonts.googleapis.com/css?family=Bitter',
            ],
            [
                'name' => 'Courier New',
                'font' => 'Courier New, Courier, Lucida Sans Typewriter, Lucida Typewriter, monospace',
            ],
            [
                'name' => 'Droid Serif',
                'font' => 'Droid Serif, Georgia, Times, Times New Roman, serif',
                'url'  => 'https://fonts.googleapis.com/css?family=Droid+Serif',
            ],
            [
                'name' => 'Georgia',
                'font' => 'Georgia, Times, Times New Roman, serif',
            ],
            [
                'name' => 'Helvetica',
                'font' => 'Helvetica Neue, Helvetica, Arial, sans-serif',
            ],
            [
                'name' => 'Lato',
                'font' => 'Lato, Tahoma, Verdana, Segoe, sans-serif',
                'url'  => 'https://fonts.googleapis.com/css?family=Lato',
            ],
            [
                'name' => 'Lucida Sans Unicode',
                'font' => 'Lucida Sans Unicode, Lucida Grande, Lucida Sans, Geneva, Verdana, sans-serif',
            ],
            [
                'name' => 'Montserrat',
                'font' => 'Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif',
                'url'  => 'https://fonts.googleapis.com/css?family=Montserrat',
            ],
            [
                'name' => 'Open Sans',
                'font' => 'Open Sans, Helvetica Neue, Helvetica, Arial, sans-serif',
                'url'  => 'https://fonts.googleapis.com/css?family=Open+Sans',
            ],
            [
                'name' => 'Roboto',
                'font' => 'Roboto, Tahoma, Verdana, Segoe, sans-serif',
                'url'  => 'https://fonts.googleapis.com/css?family=Roboto',
            ],
            [
                'name' => 'Source Sans Pro',
                'font' => 'Source Sans Pro, Tahoma, Verdana, Segoe, sans-serif',
                'url'  => 'https://fonts.googleapis.com/css?family=Source+Sans+Pro',
            ],
            [
                'name' => 'Tahoma',
                'font' => 'Tahoma, Geneva, Segoe, sans-serif',
            ],
            [
                'name' => 'Times New Roman',
                'font' => 'TimesNewRoman, Times New Roman, Times, Beskerville, Georgia, serif',
            ],
            [
                'name' => 'Trebuchet MS',
                'font' => 'Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif',
            ],
            [
                'name' => 'Ubuntu',
                'font' => 'Ubuntu, Tahoma, Verdana, Segoe, sans-serif',
                'url'  => 'https://fonts.googleapis.com/css?family=Ubuntu',
            ],
            [
                'name' => 'Verdana',
                'font' => 'Verdana, Geneva, sans-serif',
            ],
            [
                'name' => 'ヒラギノ角ゴ Pro W3',
                'font' => 'ヒラギノ角ゴ Pro W3, Hiragino Kaku Gothic Pro,Osaka, メイリオ, Meiryo, ＭＳ Ｐゴシック, MS PGothic, sans-serif',
            ],
            [
                'name' => 'メイリオ',
                'font' => 'メイリオ, Meiryo, ＭＳ Ｐゴシック, MS PGothic, ヒラギノ角ゴ Pro W3, Hiragino Kaku Gothic Pro,Osaka, sans-serif',
            ],
        ],
        'composer_updates'                                        => false,
        'redis_primary_only'                                      => false,
        MailVotech\CoreBundle\Shortener\Shortener::SHORTENER_SERVICE  => null,
        'gdpr_user_purge_threshold'                               => 1095, // Minimum no. of days a user has to be inactive to get picked up by `mailvotech:maintenance:cleanup --gdpr`
        'support_mailvotech_enabled'                                  => true,
    ],
];
