<?php

declare(strict_types=1);

namespace MailVotechPlugin\MailVotechFocusBundle\Tests\Functional\Model;

use MailVotech\CoreBundle\Test\MailVotechMysqlTestCase;
use MailVotech\FormBundle\Entity\Field;
use MailVotech\FormBundle\Entity\Form;
use MailVotech\LeadBundle\Entity\Lead;
use MailVotech\LeadBundle\Tracker\ContactTracker;
use MailVotechPlugin\MailVotechFocusBundle\Entity\Focus;
use MailVotechPlugin\MailVotechFocusBundle\Model\FocusModel;

final class FocusFormAutoFillTest extends MailVotechMysqlTestCase
{
    protected function setUp(): void
    {
        $this->configParams['form_field_autofill'] = true;

        parent::setUp();
    }

    /**
     * As the Focus Items are generated by JS we cannot use a route to assert if the form is prefilled.
     * Instead we will generate the Focus content directly via the Focus Model and check the form HTML.
     */
    public function testFormAutoFillInFocusItemOnLandingPage(): void
    {
        // Step 1: Create a form with an email field that has auto-fill enabled
        $form = new Form();
        $form->setName('Test Form for Focus');
        $form->setAlias('testformforfocus');

        $emailField = new Field();
        $emailField->setLabel('Email');
        $emailField->setType('email');
        $emailField->setAlias('email');
        $emailField->setIsRequired(true);
        $emailField->setForm($form);
        $emailField->setOrder(1);
        $emailField->setIsAutoFill(true);
        $emailField->setMappedObject('contact');
        $emailField->setMappedField('email');

        $form->addField('email', $emailField);

        $this->em->persist($form);
        $this->em->flush();

        // Step 2: Create a Focus item using this form
        $focus = new Focus();
        $focus->setName('Test Focus Item');
        $focus->setType('form');
        $focus->setStyle('bar');
        $focus->setForm($form);
        $focus->setHtmlMode('basic');
        $focus->setWebsite(1);
        $focus->setProperties([
            'bar' => [
                'push_page'  => true,
                'placement'  => 'top',
                'size'       => 'large',
                'sticky'     => false,
                'allow_hide' => true,
            ],
            'colors' => [
                'primary'     => '3498db',
                'text'        => 'ffffff',
                'button'      => 'ffffff',
                'button_text' => '3498db',
            ],
            'size'    => '600px',
            'content' => [
                'headline' => 'Subscribe to our newsletter',
                'font'     => 'Arial, sans-serif',
            ],
        ]);

        $this->em->persist($focus);
        $this->em->flush();

        // Step 3: Create a contact with email
        $contact = new Lead();
        $contact->setEmail('test-autofill@example.com');
        $this->em->persist($contact);
        $this->em->flush();

        // Step 4: Track the contact using setSystemContact (bypasses HTTP request requirement)
        /** @var ContactTracker $contactTracker */
        $contactTracker = self::getContainer()->get(ContactTracker::class);
        $contactTracker->setSystemContact($contact);

        // Step 5: Generate Focus content directly
        /** @var FocusModel $focusModel */
        $focusModel = self::getContainer()->get(FocusModel::class);
        $content    = $focusModel->getContent($focus->toArray());

        // Step 6: Verify the generated form HTML contains auto-filled email value
        // getContent returns an array with 'focus' and 'form' keys
        $formHtml = $content['form'];
        $this->assertStringContainsString('name="mailvotechform[email]"', (string) $formHtml);
        $this->assertStringContainsString('value="test-autofill@example.com"', (string) $formHtml);
        $this->assertStringContainsString('type="email"', (string) $formHtml);
    }
}
